apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: "Ktest"
  annotations:
    gocd.org/pipelines: backstage,backstage-pr,backstage-builder
spec:
  type: service
  owner: user:guest
  lifecycle: experimental
